version: "3.7"
services:
  jaeger:
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    container_name: jaeger
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - "ES_SERVER_URLS=http://elasticsearch:9200"
      - ES_TAGS_AS_FIELDS_ALL=true
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "16686:16686"
    networks:
      - insult-me
    image: jaegertracing/all-in-one:latest
  elasticsearch:
    container_name: elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - insult-me
    image: "docker.elastic.co/elasticsearch/elasticsearch:6.8.0"
  kibana:
    links:
      - elasticsearch
    container_name: kibana
    ports:
      - "5601:5601"
    networks:
      - insult-me
    image: "docker.elastic.co/kibana/kibana:6.8.0"
  redis:
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - insult-me
    image: "redis:alpine"
  mongodb:
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    networks:
      - insult-me
    image: mongo:latest

volumes:
  mongodb_data:

networks:
  insult-me:
